export const REQUEST_GUITARS_IN_COLLECTION = 'REQUEST_GUITARS_IN_COLLECTION';
export const RECEIVE_GUITARS_IN_COLLECTION = 'RECEIVE_GUITARS_IN_COLLECTION';
export const REQUEST_GUITARS_IN_WISHLIST = 'REQUEST_GUITARS_IN_WISHLIST';
export const RECEIVE_GUITARS_IN_WISHLIST = 'RECEIVE_GUITARS_IN_WISHLIST';
