export const initialState = {
  guitarsInCollection: [],
  ampsInCollection: [],
  pedalsInCollection: [],
  guitarsInWishlist: [],
  ampsInWishlist: [],
  pedalsInWishlist: []
  // guitarsInCollection: [
  //   {
  //       bodyWood: "Mahogany",
  //       finish: "Lacquer",
  //       color: "Ebony",
  //       binding: "5-Ply",
  //       neckWood: "Mahogany",
  //       neckType: "Set",
  //       neckProfile: "1960's Slim Taper",
  //       fretboardWood: "Ebony",
  //       fretboardRadius: 12,
  //       frets: 22,
  //       fretMaterial: "Gibson Style",
  //       inlays: "Mother of Pearl Block",
  //       nutMaterial: "Bone",
  //       nutWidth: 1.6875,
  //       scaleLength: 24.75,
  //       neckPickup: "Humbucker",
  //       middlePickup: "N/A",
  //       bridgePickup: "Humbucker",
  //       volumePots: "500K CTS",
  //       tonePots: "500K CTS",
  //       capacitor: "Sprangue .022 uf",
  //       tuners: "Grover Rotomatic",
  //       tunerButtons: "Nickel Keystone",
  //       bridge: "Roller",
  //       tailpiece: "Bigsby B7",
  //       guitarSwitch: "3-way",
  //       knobs: "Bellhat",
  //       pickguard: "5-Ply Black",
  //       controls: "Volume, Tone",
  //       guitarCase: "Gibson Hardcase",
  //       id: 1,
  //       manufacturer: "Gibson",
  //       model: "Les Paul Custom",
  //       country: "USA",
  //       serialNumber: "xxx",
  //       description: "old",
  //       year: 1999,
  //       weight: 10.8,
  //       imageUrl: "https://www.mansons.co.uk/userfiles/shop/products/main/main_6278.jpg",
  //       current: true,
  //       wishlist: false,
  //       paid: 1500,
  //       sold: 0
  //   },
  //   {
  //       bodyWood: "Mahogany",
  //       finish: "Lacquer",
  //       color: "Ebony",
  //       binding: "5-Ply",
  //       neckWood: "Mahogany",
  //       neckType: "Set",
  //       neckProfile: "1960's Slim Taper",
  //       fretboardWood: "Ebony",
  //       fretboardRadius: 12,
  //       frets: 22,
  //       fretMaterial: "Gibson Style",
  //       inlays: "Mother of Pearl Block",
  //       nutMaterial: "Bone",
  //       nutWidth: 1.6875,
  //       scaleLength: 24.75,
  //       neckPickup: "Humbucker",
  //       middlePickup: "N/A",
  //       bridgePickup: "Humbucker",
  //       volumePots: "500K CTS",
  //       tonePots: "500K CTS",
  //       capacitor: "Sprangue .022 uf",
  //       tuners: "Grover Rotomatic",
  //       tunerButtons: "Nickel Keystone",
  //       bridge: "Roller",
  //       tailpiece: "Bigsby B7",
  //       guitarSwitch: "3-way",
  //       knobs: "Bellhat",
  //       pickguard: "5-Ply Black",
  //       controls: "Volume, Tone",
  //       guitarCase: "Gibson Hardcase",
  //       id: 2,
  //       manufacturer: "Gibson",
  //       model: "Les Paul Custom",
  //       country: "USA",
  //       serialNumber: "xxx",
  //       description: "old",
  //       year: 1999,
  //       weight: 10.8,
  //       imageUrl: "https://cdn.shopify.com/s/files/1/0703/6443/products/tmg-guitar-company-gatton_2048x2048.jpg?v=1435610374",
  //       current: true,
  //       wishlist: false,
  //       paid: 1500,
  //       sold: 0
  //   },
  //   {
  //       bodyWood: "Mahogany",
  //       finish: "Lacquer",
  //       color: "Ebony",
  //       binding: "5-Ply",
  //       neckWood: "Mahogany",
  //       neckType: "Set",
  //       neckProfile: "1960's Slim Taper",
  //       fretboardWood: "Ebony",
  //       fretboardRadius: 12,
  //       frets: 22,
  //       fretMaterial: "Gibson Style",
  //       inlays: "Mother of Pearl Block",
  //       nutMaterial: "Bone",
  //       nutWidth: 1.6875,
  //       scaleLength: 24.75,
  //       neckPickup: "Humbucker",
  //       middlePickup: "N/A",
  //       bridgePickup: "Humbucker",
  //       volumePots: "500K CTS",
  //       tonePots: "500K CTS",
  //       capacitor: "Sprangue .022 uf",
  //       tuners: "Grover Rotomatic",
  //       tunerButtons: "Nickel Keystone",
  //       bridge: "Roller",
  //       tailpiece: "Bigsby B7",
  //       guitarSwitch: "3-way",
  //       knobs: "Bellhat",
  //       pickguard: "5-Ply Black",
  //       controls: "Volume, Tone",
  //       guitarCase: "Gibson Hardcase",
  //       id: 3,
  //       manufacturer: "Gibson",
  //       model: "Les Paul Custom",
  //       country: "USA",
  //       serialNumber: "xxx",
  //       description: "old",
  //       year: 1999,
  //       weight: 10.8,
  //       imageUrl: "https://www.mansons.co.uk/userfiles/shop/products/main/main_6278.jpg",
  //       current: true,
  //       wishlist: false,
  //       paid: 1500,
  //       sold: 0
  //   },
  //   {
  //       bodyWood: "Mahogany",
  //       finish: "Lacquer",
  //       color: "Ebony",
  //       binding: "5-Ply",
  //       neckWood: "Mahogany",
  //       neckType: "Set",
  //       neckProfile: "1960's Slim Taper",
  //       fretboardWood: "Ebony",
  //       fretboardRadius: 12,
  //       frets: 22,
  //       fretMaterial: "Gibson Style",
  //       inlays: "Mother of Pearl Block",
  //       nutMaterial: "Bone",
  //       nutWidth: 1.6875,
  //       scaleLength: 24.75,
  //       neckPickup: "Humbucker",
  //       middlePickup: "N/A",
  //       bridgePickup: "Humbucker",
  //       volumePots: "500K CTS",
  //       tonePots: "500K CTS",
  //       capacitor: "Sprangue .022 uf",
  //       tuners: "Grover Rotomatic",
  //       tunerButtons: "Nickel Keystone",
  //       bridge: "Roller",
  //       tailpiece: "Bigsby B7",
  //       guitarSwitch: "3-way",
  //       knobs: "Bellhat",
  //       pickguard: "5-Ply Black",
  //       controls: "Volume, Tone",
  //       guitarCase: "Gibson Hardcase",
  //       id: 4,
  //       manufacturer: "Gibson",
  //       model: "Les Paul Custom",
  //       country: "USA",
  //       serialNumber: "xxx",
  //       description: "old",
  //       year: 1999,
  //       weight: 10.8,
  //       imageUrl: "https://i.ebayimg.com/images/g/EoQAAOSwxKtYAV8k/s-l300.jpg",
  //       current: true,
  //       wishlist: false,
  //       paid: 1500,
  //       sold: 0
  //   }
  // ],
  // ampsInCollection: [
  //   {
  //     instrument: "Guitar",
  //     type: "Combo",
  //     power: 40,
  //     cabinetWood: "Pine",
  //     finish: "Tweed",
  //     grillCloth: "Ox Blood",
  //     width: 12,
  //     depth: 13,
  //     height: 14,
  //     electronics: "Hand-Wired",
  //     speakers: "Jensen",
  //     tubes: "two 6V6 power tubes, four 12AX7 preamp tubes, 5U4 rectifier tube",
  //     reverb: "None",
  //     tremolo: "None",
  //     externalSpeaker: "1/4\" Jack",
  //     handle: "Humbucker",
  //     knobs: "500K CTS",
  //     jewelLight: "500K CTS",
  //     controlPanel: "Sprangue .022 uf",
  //     logo: "Grover Rotomatic",
  //     tiltLegs: "Nickel Keystone",
  //     feet: "Roller",
  //     controls: "Bigsby B7",
  //     cover: "3-way",
  //     id: 5,
  //     manufacturer: "Fender",
  //     model: "Bandmaster",
  //     country: "USA",
  //     serialNumber: "xxx",
  //     description: "old",
  //     year: 2007,
  //     weight: 45.7,
  //     imageUrl: "https://media.sweetwater.com/api/i/q-82__ha-7c2b7cd6e86396e3__hmac-c08058d55adce5256f59acaa5d50cc559a7db0bc/images/items/750/57BandMaster-large.jpg",
  //     current: true,
  //     wishlist: false,
  //     paid: 1500,
  //     sold: 0
  //   },
  //   {
  //     instrument: "Guitar",
  //     type: "Combo",
  //     power: 40,
  //     cabinetWood: "Pine",
  //     finish: "Tweed",
  //     grillCloth: "Ox Blood",
  //     width: 12,
  //     depth: 13,
  //     height: 14,
  //     electronics: "Hand-Wired",
  //     speakers: "Jensen",
  //     tubes: "two 6V6 power tubes, four 12AX7 preamp tubes, 5U4 rectifier tube",
  //     reverb: "None",
  //     tremolo: "None",
  //     externalSpeaker: "1/4\" Jack",
  //     handle: "Humbucker",
  //     knobs: "500K CTS",
  //     jewelLight: "500K CTS",
  //     controlPanel: "Sprangue .022 uf",
  //     logo: "Grover Rotomatic",
  //     tiltLegs: "Nickel Keystone",
  //     feet: "Roller",
  //     controls: "Bigsby B7",
  //     cover: "3-way",
  //     id: 6,
  //     manufacturer: "Fender",
  //     model: "Bandmaster",
  //     country: "USA",
  //     serialNumber: "xxx",
  //     description: "old",
  //     year: 2007,
  //     weight: 45.7,
  //     imageUrl: "https://media.sweetwater.com/api/i/q-82__ha-7c2b7cd6e86396e3__hmac-c08058d55adce5256f59acaa5d50cc559a7db0bc/images/items/750/57BandMaster-large.jpg",
  //     current: true,
  //     wishlist: false,
  //     paid: 1500,
  //     sold: 0
  //   },
  //   {
  //     instrument: "Guitar",
  //     type: "Combo",
  //     power: 40,
  //     cabinetWood: "Pine",
  //     finish: "Tweed",
  //     grillCloth: "Ox Blood",
  //     width: 12,
  //     depth: 13,
  //     height: 14,
  //     electronics: "Hand-Wired",
  //     speakers: "Jensen",
  //     tubes: "two 6V6 power tubes, four 12AX7 preamp tubes, 5U4 rectifier tube",
  //     reverb: "false",
  //     tremolo: "false",
  //     externalSpeaker: "1/4\" Jack",
  //     handle: "Humbucker",
  //     knobs: "500K CTS",
  //     jewelLight: "500K CTS",
  //     controlPanel: "Sprangue .022 uf",
  //     logo: "Grover Rotomatic",
  //     tiltLegs: "Nickel Keystone",
  //     feet: "Roller",
  //     controls: "Bigsby B7",
  //     cover: "3-way",
  //     id: 7,
  //     manufacturer: "Fender",
  //     model: "Bandmaster",
  //     country: "USA",
  //     serialNumber: "xxx",
  //     description: "old",
  //     year: 2007,
  //     weight: 45.7,
  //     imageUrl: "https://media.sweetwater.com/api/i/q-82__ha-7c2b7cd6e86396e3__hmac-c08058d55adce5256f59acaa5d50cc559a7db0bc/images/items/750/57BandMaster-large.jpg",
  //     current: true,
  //     wishlist: false,
  //     paid: 1500,
  //     sold: 0
  //   },
  //   {
  //     instrument: "Guitar",
  //     type: "Combo",
  //     power: 40,
  //     cabinetWood: "Pine",
  //     finish: "Tweed",
  //     grillCloth: "Ox Blood",
  //     width: 12,
  //     depth: 13,
  //     height: 14,
  //     electronics: "Hand-Wired",
  //     speakers: "Jensen",
  //     tubes: "two 6V6 power tubes, four 12AX7 preamp tubes, 5U4 rectifier tube",
  //     reverb: "false",
  //     tremolo: "false",
  //     externalSpeaker: "1/4\" Jack",
  //     handle: "Humbucker",
  //     knobs: "500K CTS",
  //     jewelLight: "500K CTS",
  //     controlPanel: "Sprangue .022 uf",
  //     logo: "Grover Rotomatic",
  //     tiltLegs: "Nickel Keystone",
  //     feet: "Roller",
  //     controls: "Bigsby B7",
  //     cover: "3-way",
  //     id: 8,
  //     manufacturer: "Fender",
  //     model: "Bandmaster",
  //     country: "USA",
  //     serialNumber: "xxx",
  //     description: "old",
  //     year: 2007,
  //     weight: 45.7,
  //     imageUrl: "https://media.sweetwater.com/api/i/q-82__ha-7c2b7cd6e86396e3__hmac-c08058d55adce5256f59acaa5d50cc559a7db0bc/images/items/750/57BandMaster-large.jpg",
  //     current: true,
  //     wishlist: false,
  //     paid: 1500,
  //     sold: 0
  //   }
  // ],
  // pedalsInCollection: [
  //   {
  //     type: "Overdrive",
  //     power: "9V-18V",
  //     width: 1.2,
  //     depth: 1,
  //     height: 3.2,
  //     electronics: "PCB",
  //     trueBypass: false,
  //     inputImpedance: 1000000,
  //     outputImpedance: 100,
  //     currentDraw: "10-25mA",
  //     controls: "volume, Tone, Gain",
  //     features: "Buffer",
  //     id: 9,
  //     manufacturer: "Wampler",
  //     model: "Tumnus",
  //     country: "USA",
  //     serialNumber: "xxx",
  //     description: "old",
  //     year: 2017,
  //     weight: 34,
  //     imageUrl: "https://sc1.musik-produktiv.com/pic-010082870xl/wampler-tumnus.jpg",
  //     current: true,
  //     wishlist: false,
  //     paid: 125,
  //     sold: 0
  //   },
  //   {
  //     type: "Overdrive",
  //     power: "9V-18V",
  //     width: 1.2,
  //     depth: 1,
  //     height: 3.2,
  //     electronics: "PCB",
  //     trueBypass: false,
  //     inputImpedance: 1000000,
  //     outputImpedance: 100,
  //     currentDraw: "10-25mA",
  //     controls: "volume, Tone, Gain",
  //     features: "Buffer",
  //     id: 10,
  //     manufacturer: "Wampler",
  //     model: "Tumnus",
  //     country: "USA",
  //     serialNumber: "xxx",
  //     description: "old",
  //     year: 2017,
  //     weight: 34,
  //     imageUrl: "https://sc1.musik-produktiv.com/pic-010082870xl/wampler-tumnus.jpg",
  //     current: true,
  //     wishlist: false,
  //     paid: 125,
  //     sold: 0
  //   },
  //   {
  //     type: "Overdrive",
  //     power: "9V-18V",
  //     width: 1.2,
  //     depth: 1,
  //     height: 3.2,
  //     electronics: "PCB",
  //     trueBypass: false,
  //     inputImpedance: 1000000,
  //     outputImpedance: 100,
  //     currentDraw: "10-25mA",
  //     controls: "volume, Tone, Gain",
  //     features: "Buffer",
  //     id: 11,
  //     manufacturer: "Wampler",
  //     model: "Tumnus",
  //     country: "USA",
  //     serialNumber: "xxx",
  //     description: "old",
  //     year: 2017,
  //     weight: 34,
  //     imageUrl: "https://sc1.musik-produktiv.com/pic-010082870xl/wampler-tumnus.jpg",
  //     current: true,
  //     wishlist: false,
  //     paid: 125,
  //     sold: 0
  //   },
  //   {
  //     type: "Overdrive",
  //     power: "9V-18V",
  //     width: 1.2,
  //     depth: 1,
  //     height: 3.2,
  //     electronics: "PCB",
  //     trueBypass: false,
  //     inputImpedance: 1000000,
  //     outputImpedance: 100,
  //     currentDraw: "10-25mA",
  //     controls: "volume, Tone, Gain",
  //     features: "Buffer",
  //     id: 12,
  //     manufacturer: "Wampler",
  //     model: "Tumnus",
  //     country: "USA",
  //     serialNumber: "xxx",
  //     description: "old",
  //     year: 2017,
  //     weight: 34,
  //     imageUrl: "https://sc1.musik-produktiv.com/pic-010082870xl/wampler-tumnus.jpg",
  //     current: true,
  //     wishlist: false,
  //     paid: 125,
  //     sold: 0
  //   }
  // ],
  // guitarsInWishlist: [
  //   {
  //       bodyWood: "Mahogany",
  //       finish: "Lacquer",
  //       color: "Ebony",
  //       binding: "5-Ply",
  //       neckWood: "Mahogany",
  //       neckType: "Set",
  //       neckProfile: "1960's Slim Taper",
  //       fretboardWood: "Ebony",
  //       fretboardRadius: 12,
  //       frets: 22,
  //       fretMaterial: "Gibson Style",
  //       inlays: "Mother of Pearl Block",
  //       nutMaterial: "Bone",
  //       nutWidth: 1.6875,
  //       scaleLength: 24.75,
  //       neckPickup: "Humbucker",
  //       middlePickup: "N/A",
  //       bridgePickup: "Humbucker",
  //       volumePots: "500K CTS",
  //       tonePots: "500K CTS",
  //       capacitor: "Sprangue .022 uf",
  //       tuners: "Grover Rotomatic",
  //       tunerButtons: "Nickel Keystone",
  //       bridge: "Roller",
  //       tailpiece: "Bigsby B7",
  //       guitarSwitch: "3-way",
  //       knobs: "Bellhat",
  //       pickguard: "5-Ply Black",
  //       controls: "Volume, Tone",
  //       guitarCase: "Gibson Hardcase",
  //       id: 13,
  //       manufacturer: "Gibson",
  //       model: "Les Paul Custom",
  //       country: "USA",
  //       serialNumber: "xxx",
  //       description: "old",
  //       year: 1999,
  //       weight: 10.8,
  //       imageUrl: "https://www.mansons.co.uk/userfiles/shop/products/main/main_6278.jpg",
  //       current: true,
  //       wishlist: true,
  //       paid: 1500,
  //       sold: 0
  //   }
  // ],
  // ampsInWishlist: [
  //   {
  //     instrument: "Guitar",
  //     type: "Combo",
  //     power: 40,
  //     cabinetWood: "Pine",
  //     finish: "Tweed",
  //     grillCloth: "Ox Blood",
  //     width: 12,
  //     depth: 13,
  //     height: 14,
  //     electronics: "Hand-Wired",
  //     speakers: "Jensen",
  //     tubes: "two 6V6 power tubes, four 12AX7 preamp tubes, 5U4 rectifier tube",
  //     reverb: "false",
  //     tremolo: "false",
  //     externalSpeaker: "1/4\" Jack",
  //     handle: "Humbucker",
  //     knobs: "500K CTS",
  //     jewelLight: "500K CTS",
  //     controlPanel: "Sprangue .022 uf",
  //     logo: "Grover Rotomatic",
  //     tiltLegs: "Nickel Keystone",
  //     feet: "Roller",
  //     controls: "Bigsby B7",
  //     cover: "3-way",
  //     id: 14,
  //     manufacturer: "Fender",
  //     model: "Bandmaster",
  //     country: "USA",
  //     serialNumber: "xxx",
  //     description: "old",
  //     year: 2007,
  //     weight: 45.7,
  //     imageUrl: "https://media.sweetwater.com/api/i/q-82__ha-7c2b7cd6e86396e3__hmac-c08058d55adce5256f59acaa5d50cc559a7db0bc/images/items/750/57BandMaster-large.jpg",
  //     current: true,
  //     wishlist: true,
  //     paid: 1500,
  //     sold: 0
  //   }
  // ],
  // pedalsInWishlist: [
  //   {
  //     type: "Overdrive",
  //     power: "9V-18V",
  //     width: 1.2,
  //     depth: 1,
  //     height: 3.2,
  //     electronics: "PCB",
  //     trueBypass: false,
  //     inputImpedance: 1000000,
  //     outputImpedance: 100,
  //     currentDraw: "10-25mA",
  //     controls: "volume, Tone, Gain",
  //     features: "Buffer",
  //     id: 15,
  //     manufacturer: "Wampler",
  //     model: "Tumnus",
  //     country: "USA",
  //     serialNumber: "xxx",
  //     description: "old",
  //     year: 2017,
  //     weight: 34,
  //     imageUrl: "https://sc1.musik-produktiv.com/pic-010082870xl/wampler-tumnus.jpg",
  //     current: true,
  //     wishlist: true,
  //     paid: 125,
  //     sold: 0
  //   }
  // ]
}
